# Generated by Django 5.2.5 on 2025-09-19 19:07

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuncionarioHotel',
            fields=[
                ('funcionario_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(help_text='Nombre del funcionario', max_length=100)),
                ('telefono', models.CharField(help_text='Número de teléfono en formato internacional (ej: +56912345678)', max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='El número de teléfono debe estar en formato internacional', regex='^\\+?1?\\d{9,15}$')])),
                ('cargo', models.CharField(blank=True, help_text='Cargo del funcionario', max_length=50, null=True)),
                ('puede_confirmar_llegadas', models.BooleanField(default=True, help_text='Puede confirmar llegadas de clientes')),
                ('puede_cancelar_reservas', models.BooleanField(default=False, help_text='Puede cancelar reservas')),
                ('puede_modificar_reservas', models.BooleanField(default=False, help_text='Puede modificar reservas existentes')),
                ('activo', models.BooleanField(default=True, help_text='Funcionario activo en el sistema')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Funcionario del Hotel',
                'verbose_name_plural': 'Funcionarios del Hotel',
                'db_table': 'funcionarios_hotel',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='EstadoConversacion',
            fields=[
                ('estado_conversacion_id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=50)),
                ('paso_actual', models.CharField(max_length=50)),
                ('datos_reserva', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.cliente')),
            ],
            options={
                'db_table': 'estados_conversacion',
            },
        ),
        migrations.CreateModel(
            name='ReservaWhatsApp',
            fields=[
                ('reserva_id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_reserva', models.CharField(choices=[('por_horas', 'Por Horas'), ('noche_completa', 'Noche Completa')], default='por_horas', help_text='Tipo de reserva solicitada', max_length=20)),
                ('fecha_reserva', models.DateField(help_text='Fecha para la cual se hace la reserva')),
                ('hora_inicio', models.TimeField(help_text='Hora de inicio de la reserva')),
                ('hora_fin', models.TimeField(help_text='Hora de fin de la reserva')),
                ('numero_personas', models.PositiveSmallIntegerField(default=2, help_text='Número de personas para la reserva')),
                ('observaciones', models.TextField(blank=True, help_text='Observaciones adicionales del cliente', null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('en_proceso', 'En Proceso'), ('llegada_confirmada', 'Llegada Confirmada'), ('completada', 'Completada'), ('cancelada', 'Cancelada'), ('no_show', 'No Show')], default='pendiente', help_text='Estado actual de la reserva', max_length=20)),
                ('nombre_contacto', models.CharField(blank=True, help_text='Nombre del contacto principal', max_length=100, null=True)),
                ('precio_total', models.DecimalField(decimal_places=2, help_text='Precio total de la reserva', max_digits=10)),
                ('precio_por_hora', models.DecimalField(decimal_places=2, help_text='Precio por hora aplicado', max_digits=10)),
                ('horas_reservadas', models.PositiveSmallIntegerField(help_text='Número de horas reservadas')),
                ('fecha_hora_llegada', models.DateTimeField(blank=True, help_text='Fecha y hora de llegada confirmada', null=True)),
                ('confirmada_por_funcionario', models.CharField(blank=True, help_text='Teléfono del funcionario que confirmó la llegada', max_length=20, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('conversacion_id', models.CharField(blank=True, help_text='ID de la conversación donde se realizó la reserva', max_length=50, null=True)),
                ('paso_actual', models.CharField(default='inicio', help_text='Paso actual en el proceso de reserva', max_length=50)),
                ('datos_temporales', models.JSONField(blank=True, default=dict, help_text='Datos temporales durante el proceso de reserva')),
                ('cliente', models.ForeignKey(help_text='Cliente que realiza la reserva', on_delete=django.db.models.deletion.PROTECT, related_name='reservas_whatsapp', to='api.cliente')),
                ('habitacion', models.ForeignKey(help_text='Habitación reservada', on_delete=django.db.models.deletion.PROTECT, related_name='reservas_whatsapp', to='api.habitacion')),
            ],
            options={
                'verbose_name': 'Reserva WhatsApp',
                'verbose_name_plural': 'Reservas WhatsApp',
                'db_table': 'reservas_whatsapp',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='ProcesoReserva',
            fields=[
                ('proceso_id', models.AutoField(primary_key=True, serialize=False)),
                ('paso_actual', models.CharField(default='inicio', help_text='Paso actual en el proceso de reserva', max_length=50)),
                ('datos_temporales', models.JSONField(default=dict, help_text='Datos recopilados durante el proceso')),
                ('conversacion_id', models.CharField(help_text='ID de la conversación asociada', max_length=50)),
                ('completado', models.BooleanField(default=False, help_text='Proceso completado exitosamente')),
                ('cancelado', models.BooleanField(default=False, help_text='Proceso cancelado por el usuario')),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('fecha_finalizacion', models.DateTimeField(blank=True, help_text='Fecha de finalización del proceso', null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procesos_reserva', to='api.cliente')),
                ('reserva_creada', models.ForeignKey(blank=True, help_text='Reserva creada al completar el proceso', null=True, on_delete=django.db.models.deletion.SET_NULL, to='reservas.reservawhatsapp')),
            ],
            options={
                'verbose_name': 'Proceso de Reserva',
                'verbose_name_plural': 'Procesos de Reserva',
                'db_table': 'procesos_reserva',
                'ordering': ['-fecha_inicio'],
            },
        ),
    ]
