# Generated by Django 5.2.5 on 2025-09-19 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_reserva_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseconocimiento',
            name='palabras_clave',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
