# Generated by Django 5.2.5 on 2025-09-19 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_baseconocimiento_palabras_clave'),
    ]

    operations = [
        migrations.RenameField(
            model_name='baseconocimiento',
            old_name='ultima_actualizacion',
            new_name='fecha_modificacion',
        ),
        migrations.AddField(
            model_name='baseconocimiento',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
