# Generated by Django 5.2.5 on 2025-09-25 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_ultima_actualizacion_baseconocimiento_fecha_modificacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='fecha_llegada',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
