# Generated by Django 5.2.5 on 2025-09-25 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_reserva_fecha_llegada'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='duracion',
            field=models.IntegerField(default=6, help_text='Duración en horas'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reserva',
            name='origen',
            field=models.CharField(choices=[('web', 'Web'), ('whatsapp', 'WhatsApp'), ('telefono', 'Teléfono')], default='web', max_length=20),
        ),
        migrations.AddField(
            model_name='reserva',
            name='precio_total',
            field=models.DecimalField(decimal_places=2, default=10000, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reserva',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
